export const redirects = [
  ["/curseforge", "https://www.curseforge.com/minecraft/modpacks/fabulously-optimized"],
  ["/changelog", "https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md"],
  ["/discord", "https://discord.gg/fabulously-optimized-859124104644788234"],
  ["/github", "https://github.com/Fabulously-Optimized/fabulously-optimized"],
  ["/host", "https://www.bisecthosting.com/clients/aff.php?aff=2604"],
  ["/install", "https://wiki.download.fo/readme/install-instructions"],
  ["/issues", "https://github.com/Fabulously-Optimized/fabulosuly-optimized/issues"],
  ["/mastodon", "https://floss.social/@fabulouslyoptimized"],
  ["/minecraft", "https://punktid.com/minecraft-java-bedrock?ref=robotkoer"],
  ["/modrinth", "https://modrinth.com/modpack/fabulously-optimized"],
  ["/mods", "https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/INCLUDED-MODS.md"],
  ["/rate", "https://alternativeto.net/software/fabulously-optimized/about/"],
  ["/terms", "https://wiki.download.fo/readme/disclaimers"],
  ["/thanks", "https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CONTRIBUTING.md"],
  ["/translate", "https://wiki.download.fo/readme/language-support"],
  ["/update", "https://wiki.download.fo/readme/update-instructions"],
  ["/wiki", "https://wiki.download.fo"],
  ["/vanilla", "https://download.fo/mrpack-to-zip/vanilla"]
]
